# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@stable'
    'frameworks/ki18n': '@stable'
    'frameworks/karchive': '@stable'
    'frameworks/kio': '@stable'

Options:
  require-passing-tests-on: [ '@all' ]
